### ISSUE TITLE
Integration Tests fail sporadically

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#116]
Issue #84 set up Integration Tests to be run against a running CloudFoundry app instance. Often, the rest requests fail with 502 (due to the CF reverse proxies not having refreshed to point to the newly deployed app instance).

**Comment by j-barber** [comment]
@GalateaEric says there's some delay between starting an app in CF and when the reverse proxies route traffic to the new instance. Kent got ITs working reliably by introducing some sleep time to the pipeline in between restarting the app on CF and running ITs.

From feature/issue-98-gradle looks like adding this as the first step in the Integration tests stage did the trick:
>            sleep time: 90, unit: 'SECONDS'

**Comment by j-barber** [comment]
We'll know this works if Jenkins builds stop failing with this error: 

> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.226 sec <<< FAILURE! - in org.galatea.starter.entrypoint.SettlementRestControllerIntegrationTest
testMissionCreation(org.galatea.starter.entrypoint.SettlementRestControllerIntegrationTest)  Time elapsed: 0.215 sec  <<< ERROR!
feign.FeignException: status 502 reading FuseServer#sendTradeAgreement(TradeAgreement[]); content:
502 Bad Gateway: Registered endpoint failed to handle the request.

	at feign.FeignException.errorStatus(FeignException.java:62)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at org.galatea.starter.entrypoint.$Proxy45.sendTradeAgreement(Unknown Source)
	at org.galatea.starter.entrypoint.SettlementRestControllerIntegrationTest.testMissionCreation(SettlementRestControllerIntegrationTest.java:51)

**Comment by j-barber** [comment]
Not conclusive evidence this solves the problem, but the build related to this PR succeeded: 

https://jenkins.fuse.galatea-associates.com/job/jenkins-pipeline/view/change-requests/job/PR-121/1/console

**Comment by j-barber** [comment]
Closing this issue -- pull request builds now succeeding reliably.
